version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 962804699607.dkr.ecr.us-west-2.amazonaws.com
      #- $(aws ecr get-login-password --no-include-email --region us-west-2)
  build:
    commands:
      - echo build Docker image on `date`
  #    - cd src
      - docker build -t capgroup2:latest .
      - docker tag capgroup2:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/capgroup2:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/capgroup2:latest